/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RwSite {
  getNavigation(sectionRef?: string | undefined | null): NavigationResponse
  renderPage(path: string): Promise<PageResponse>
  reload(): void
}

export interface BreadcrumbResponse {
  title: string
  path: string
  section?: SectionResponse
}

export declare function createSite(config: SiteConfig): RwSite

export interface DiagramsConfig {
  krokiUrl?: string
  dpi?: number
}

export interface NavigationResponse {
  items: Array<NavItemResponse>
  scope?: ScopeInfoResponse
  parentScope?: ScopeInfoResponse
}

export interface NavItemResponse {
  title: string
  path: string
  section?: SectionResponse
  children?: Array<NavItemResponse>
}

export interface PageMetaResponse {
  title?: string
  path: string
  sourceFile: string
  lastModified: string
  description?: string
  kind?: string
  vars?: any
  sectionRef: string
}

export interface PageResponse {
  meta: PageMetaResponse
  breadcrumbs: Array<BreadcrumbResponse>
  toc: Array<TocEntryResponse>
  content: string
}

export interface S3Config {
  bucket: string
  entity: string
  region?: string
  endpoint?: string
  bucketRootPath?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface ScopeInfoResponse {
  path: string
  title: string
  section: SectionResponse
}

export interface SectionResponse {
  kind: string
  name: string
}

export interface SiteConfig {
  projectDir?: string
  s3?: S3Config
  diagrams?: DiagramsConfig
}

export interface TocEntryResponse {
  level: number
  title: string
  id: string
}
