/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RwSite {
  getNavigation(sectionRef?: string | undefined | null): Promise<NavigationResponse>
  listSections(): Promise<Array<SectionEntryResponse>>
  listPages(): Promise<Array<PageEntryResponse>>
  renderPage(path: string): Promise<PageResponse>
  renderSearchDocument(path: string): Promise<SearchDocumentResponse | null>
  reload(force?: boolean | undefined | null): Promise<boolean>
}

export interface BreadcrumbResponse {
  title: string
  path: string
  section?: SectionResponse
}

export declare function createSite(config: SiteConfig): RwSite

export interface DiagramsConfig {
  krokiUrl?: string
  dpi?: number
}

export interface NavigationResponse {
  items: Array<NavItemResponse>
  scope?: ScopeInfoResponse
  parentScope?: ScopeInfoResponse
}

export interface NavItemResponse {
  title: string
  path: string
  section?: SectionResponse
  children?: Array<NavItemResponse>
}

export interface PageEntryResponse {
  /**
   * Canonical section ref (`kind:namespace/name`). Named `sectionRef` in JS
   * to match `PageMeta.sectionRef`.
   */
  sectionRef: string
  /** Page path relative to its section root (`""` for the section root). */
  subpath: string
  /** Display title. */
  title: string
}

export interface PageMetaResponse {
  title?: string
  path: string
  sourceFile: string
  lastModified: string
  description?: string
  kind?: string
  vars?: any
  sectionRef: string
  /**
   * Page path relative to its section root. Stable across whole-section
   * moves, so embedding hosts can key comments on `(sectionRef, subpath)`.
   */
  subpath: string
}

export interface PageResponse {
  meta: PageMetaResponse
  breadcrumbs: Array<BreadcrumbResponse>
  toc: Array<TocEntryResponse>
  content: string
}

/**
 * Render a comment's markdown to safe, restricted HTML.
 *
 * Produces the same `bodyHtml` the bundled viewer expects, so a host that
 * stores its own comments (for example a Backstage backend plugin) can render
 * comment bodies identically to `rw serve`. Pure and stateless — no `RwSite`
 * instance is required. Raw HTML is escaped, headings are demoted, tables
 * flattened, images dropped, and links keep their `href` only for
 * `http`/`https`/`mailto` schemes. Blank input renders to an empty string.
 */
export declare function renderCommentBody(markdown: string): Promise<string>

export interface S3Config {
  bucket: string
  entity: string
  region?: string
  endpoint?: string
  bucketRootPath?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface ScopeInfoResponse {
  path: string
  title: string
  section: SectionResponse
}

export interface SearchDocumentResponse {
  title: string
  text: string
}

export interface SectionEntryResponse {
  /**
   * Canonical section ref (`kind:namespace/name`). Named `sectionRef` in JS
   * to match `PageMeta.sectionRef`.
   */
  sectionRef: string
  /** Scope path, no leading slash (`""` for the root section). */
  path: string
  /** Ancestor section refs, nearest-first with the root last; excludes self. */
  ancestors: Array<string>
}

export interface SectionResponse {
  kind: string
  namespace: string
  name: string
}

export interface SiteConfig {
  projectDir?: string
  s3?: S3Config
  diagrams?: DiagramsConfig
}

export interface TocEntryResponse {
  level: number
  title: string
  id: string
}
