/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RwSite {
  getNavigation(sectionRef?: string | undefined | null): Promise<NavigationResponse>
  listSections(): Promise<Array<SectionEntryResponse>>
  listPages(): Promise<Array<PageEntryResponse>>
  renderPage(path: string): Promise<PageResponse>
  renderSearchDocument(path: string): Promise<SearchDocumentResponse | null>
  reload(force?: boolean | undefined | null): Promise<boolean>
}

export interface BreadcrumbResponse {
  title: string
  path: string
  /**
   * Section ref of the nearest enclosing section — the crumb's key into the
   * page response's `sectionAncestry` map.
   */
  sectionRef: string
  /** This crumb's path relative to `sectionRef`'s scope root. */
  subpath: string
}

export declare function createSite(config: SiteConfig): RwSite

export interface DiagramsConfig {
  krokiUrl?: string
  dpi?: number
}

export interface NavigationResponse {
  items: Array<NavItemResponse>
  scope?: ScopeInfoResponse
  parentScope?: ScopeInfoResponse
  /**
   * Ancestry chains for the sections reachable from this navigation view,
   * keyed by section ref.
   */
  sectionAncestry: Record<string, Array<SectionAnchorResponse>>
}

export interface NavItemResponse {
  title: string
  path: string
  section?: SectionResponse
  children?: Array<NavItemResponse>
}

export interface PageEntryResponse {
  /**
   * Canonical section ref (`kind:namespace/name`). Named `sectionRef` in JS
   * to match `PageMeta.sectionRef`.
   */
  sectionRef: string
  /** Page path relative to its section root (`""` for the section root). */
  subpath: string
  /** Display title. */
  title: string
  /**
   * Last-modified time as an RFC-3339 string (e.g.
   * `2026-07-09T10:35:00+00:00`), matching `PageMeta.lastModified`. Sourced
   * from the same per-page mtime `renderPage()` uses (git author-time for
   * clean tracked files, filesystem mtime otherwise; the S3 manifest
   * `mtimes` table for published bundles).
   *
   * Falls back to the Unix epoch (`1970-01-01T00:00:00+00:00`) when the mtime
   * is unknown — a site served from a legacy S3 manifest published before
   * per-page mtimes were recorded (republishing repopulates it), or a virtual
   * directory page that has no backing markdown file. Here "epoch" means
   * unknown, not an actual 1970 modification.
   */
  lastModified: string
}

export interface PageMetaResponse {
  title?: string
  path: string
  sourceFile: string
  lastModified: string
  description?: string
  kind?: string
  vars?: any
  sectionRef: string
  /**
   * Page path relative to its section root. Stable across whole-section
   * moves, so embedding hosts can key comments on `(sectionRef, subpath)`.
   */
  subpath: string
}

export interface PageResponse {
  meta: PageMetaResponse
  breadcrumbs: Array<BreadcrumbResponse>
  toc: Array<TocEntryResponse>
  content: string
  /**
   * Ancestry chains for the sections this page is connected to, keyed by
   * section ref.
   */
  sectionAncestry: Record<string, Array<SectionAnchorResponse>>
}

/**
 * Render a comment's markdown to safe, restricted HTML.
 *
 * Produces the same `bodyHtml` the bundled viewer expects, so a host that
 * stores its own comments (for example a Backstage backend plugin) can render
 * comment bodies identically to `rw serve`. Pure and stateless — no `RwSite`
 * instance is required. Raw HTML is escaped, headings are demoted, tables
 * flattened, images dropped, and links keep their `href` only for
 * `http`/`https`/`mailto` schemes. Blank input renders to an empty string.
 */
export declare function renderCommentBody(markdown: string): Promise<string>

export interface S3Config {
  bucket: string
  entity: string
  region?: string
  endpoint?: string
  bucketRootPath?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface ScopeInfoResponse {
  path: string
  title: string
  section: SectionResponse
}

export interface SearchDocumentResponse {
  title: string
  text: string
}

/**
 * One link in a section's ancestry chain: a section ref and the subpath of
 * that section's root.
 */
export interface SectionAnchorResponse {
  sectionRef: string
  subpath: string
}

export interface SectionEntryResponse {
  /**
   * Canonical section ref (`kind:namespace/name`). Named `sectionRef` in JS
   * to match `PageMeta.sectionRef`.
   */
  sectionRef: string
  /** Scope path, no leading slash (`""` for the root section). */
  path: string
  /** Ancestor section refs, nearest-first with the root last; excludes self. */
  ancestors: Array<string>
}

export interface SectionResponse {
  kind: string
  namespace: string
  name: string
}

export interface SiteConfig {
  projectDir?: string
  s3?: S3Config
  diagrams?: DiagramsConfig
  /**
   * Modification-time source for a `projectDir` (filesystem) site:
   * `"filesystem"` (default — a fast `stat`, reflecting on-disk edits) or
   * `"git"` (commit times, matching S3-served pages, at the cost of a
   * per-page git query). Ignored for `s3` sites (their mtimes come from the
   * published manifest). For a `projectDir` site, an unrecognized value is
   * rejected.
   */
  mtimeSource?: string
}

export interface TocEntryResponse {
  level: number
  title: string
  id: string
}
